[custom]
;设置规则标志位
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.list
ruleset=广告拦截,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising.yaml
ruleset=💬 AI&谷歌&微软服务,https://raw.githubusercontent.com/LMuniverse/ApexApple_AE1/main/rule/AI.list
ruleset=YouTube,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Loon/YouTube/YouTube.list
ruleset=💬 AI&谷歌&微软服务,https://raw.githubusercontent.com/LMuniverse/ApexApple_AE1/main/rule/Google.list
ruleset=💬 AI&谷歌&微软服务,https://raw.githubusercontent.com/LMuniverse/ApexApple_AE1/main/rule/GooglePlay.list
ruleset=💬 AI&谷歌&微软服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.list
ruleset=TikTok,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.list
ruleset=Telegram,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.list
ruleset=X,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.list
ruleset=Instagram,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Instagram/Instagram.list
ruleset=Spotify,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.list
ruleset=Facebook,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Facebook/Facebook.list
ruleset=国外流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.list
ruleset=国外流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Hulu/Hulu.list
ruleset=国外流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.list
ruleset=国外流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/HBO/HBO.list
ruleset=国外流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bahamut/Bahamut.list
ruleset=javdb,https://raw.githubusercontent.com/LMuniverse/ApexApple_AE1/main/rule/JavDB.list
ruleset=抖音,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/DouYin/DouYin.list
ruleset=小红书,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/XiaoHongShu/XiaoHongShu.list
ruleset=微博,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Weibo/Weibo.list
ruleset=快手,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/KuaiShou/KuaiShou.list
ruleset=哔哩哔哩,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.list
ruleset=知乎,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Zhihu/Zhihu.list

ruleset=DIRECT,[]GEOIP,CN
;ruleset=🚩 社交平台IP归属地,clash-classic:https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml
ruleset=兜底策略,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=兜底策略`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹`.*
custom_proxy_group=💬 AI&谷歌&微软服务`select`(^(?=.*(美国9929LSA-35|美国-大碗-高速|美国-三网平等-REAL|🇺🇸美国wave-hy|台湾静态三网|韩国S01|英国·商宽|台湾-(0[3-6]|10)|软银|美国-01|美国-05|美国S01|美国S02|英国S01|土耳其S01))(?!.*(回国|校园|游戏|教育|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|群|GAME|TG)).*)`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=TikTok`select`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=YouTube`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=Telegram`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=X`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=Instagram`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=Spotify`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=Facebook`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=国外流媒体`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇯🇵 日本节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=javdb`select`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=抖音`select`[]DIRECT`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=小红书`select`[]DIRECT`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=微博`select`[]DIRECT`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=快手`select`[]DIRECT`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=哔哩哔哩`select`[]DIRECT`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=知乎`select`[]DIRECT`[]🇭🇰 香港节点 🕹`[]🇹🇼 台湾节点 🕹`[]🇰🇷 韩国节点 🕹`[]🇸🇬 新加坡节点 🕹`[]🇺🇸 美国节点 🕹`[]🌏 全球节点 🕹
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]兜底策略
custom_proxy_group=🇭🇰 香港节点 🕹`select`(^(?=.*(🇭🇰|香港|HK|HKG|Hong))(?!.*(回国|校园|游戏|🎮|GAME)).*)
custom_proxy_group=🇹🇼 台湾节点 🕹`select`(^(?=.*(🇹🇼|台湾|TW|TWN|Tai|Taiwan))(?!.*(回国|校园|游戏|🎮|GAME)).*)
custom_proxy_group=🇯🇵 日本节点 🕹`select`(^(?=.*(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|JP|JPN|Japan))(?!.*(回国|校园|游戏|🎮|GAME)).*)
custom_proxy_group=🇰🇷 韩国节点 🕹`select`(^(?=.*(🇰🇷|韩国|韓|首尔|KR|KOR|Korea))(?!.*(回国|校园|游戏|🎮|GAME)).*)
custom_proxy_group=🇸🇬 新加坡节点 🕹`select`(^(?=.*(🇸🇬|新加坡|狮|SG|SGP|Singapore))(?!.*(回国|校园|游戏|🎮|GAME)).*)
custom_proxy_group=🇺🇸 美国节点 🕹`select`(^(?=.*(🇺🇸|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|USA|United States))(?!.*(回国|校园|游戏|🎮|GAME)).*)
custom_proxy_group=🌏 全球节点 🕹`select`(^(?=.*(.))(?!.*(群|邀请|返利|循环|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|超时|收藏|福利|好友|失联|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|Traffic|🇭🇰|港|HK|Hong|🇹🇼|台|TW|Tai|🇯🇵|日|川日|东京|大阪|泉日|埼玉|JP|Japan|🇰🇷|韩|韓|首尔|KR|Korea|🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|UnitedStates|🇸🇬|新加坡|狮|SG|Singapore)).*)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://cdn.jsdelivr.net/gh/LMuniverse/ApexApple_AE1@main/config/clash_rule_base.yaml